name: flutter_hive
description: Simple Todo app with GetX and Hive
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  json_annotation: ^4.9.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.jpg